# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "frontend/assets/dist"
  # Path to source folder
  src: "frontend/assets/app"
  # Paths to fonts
  fonts:
    - "vendor/bower/font-awesome/fonts/**/*"
    - "vendor/bower/bootstrap/fonts/**/*"
    - "frontend/assets/app/fonts/ptsans-bold/**/*"
    - "frontend/assets/app/fonts/ptsans-regular/**/*"
  # Paths to Css libraries
  css:
    front:
      - "vendor/bower/checkbo/src/0.1.4/css/checkBo.css"
      - "vendor/yiisoft/yii2-authclient/assets/authchoice.css"
      - "frontend/assets/comments/css/jquery-comments.css"
      - "frontend/assets/app/css/plugins.css"
      - "frontend/assets/app/css/main.css"
      - "frontend/assets/app/css/style.css"
    lite:
        - "vendor/yiisoft/yii2-authclient/assets/authchoice.css"
        - "lite/assets/comments/css/jquery-comments.css"
        - "lite/assets/app/css/plugins.css"
        - "lite/assets/app/css/main-mobile.css"
        - "lite/assets/app/css/style.css"
  # Paths to JavaScript libraries
  js:
    front:
      - "vendor/bower/jquery/dist/jquery.js"
      - "vendor/bower/yii2-pjax/jquery.pjax.js"
      - "vendor/bower/bootstrap/dist/js/bootstrap.js"
      - "vendor/bower/checkbo/src/0.1.4/js/checkBo.js"
      - "vendor/yiisoft/yii2/assets/yii.js"
      - "vendor/yiisoft/yii2/assets/yii.validation.js"
      - "vendor/yiisoft/yii2/assets/yii.activeForm.js"
      - "vendor/bower/jquery-textcomplete/dist/jquery.textcomplete.js"
      - "frontend/assets/app/js/authchoice.js"
      - "frontend/assets/app/js/plugins.min.js"
      - "frontend/assets/comments/js/jquery-comments.js"
      - "frontend/assets/app/js/script.js"
    lite:
      - "vendor/bower/jquery/dist/jquery.js"
      - "vendor/bower/yii2-pjax/jquery.pjax.js"
      - "vendor/bower/bootstrap/dist/js/bootstrap.js"
      - "vendor/yiisoft/yii2/assets/yii.js"
      - "vendor/yiisoft/yii2/assets/yii.validation.js"
      - "vendor/yiisoft/yii2/assets/yii.activeForm.js"
      - "vendor/bower/jquery-textcomplete/dist/jquery.textcomplete.js"
      - "frontend/assets/app/js/authchoice.js"
      - "lite/assets/app/js/plugins.min.js"
      - "lite/assets/comments/js/jquery-comments.js"
      - "lite/assets/app/js/script.js"