version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - ./:/app:delegated
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./.docker/vhosts:/etc/apache2/sites-enabled:delegated
      - ./.docker/logs:/var/log/apache2:delegated
    networks:
      vpcbr:
        ipv4_address: 172.23.0.3
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.0
    networks:
      vpcbr:
        ipv4_address: 172.23.0.4
    volumes:
      - ./backups:/backups/sof
      - /var/www/docker/sof/mongodb/sof:/data/db

  redis:
    image: redis:5.0
    restart: always
    networks:
      vpcbr:
        ipv4_address: 172.23.0.6


  mysql:
    image: mysql:5.7
    restart: always
    networks:
      vpcbr:
        ipv4_address: 172.23.0.7
    environment:
      - MYSQL_ROOT_PASSWORD=sof
      - MYSQL_DATABASE=sof
      - MYSQL_USER=sof
      - MYSQL_PASSWORD=sof


networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - subnet: 172.23.0.0/24