version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - ./:/var/www/html:delegated
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./.docker/vhosts:/etc/apache2/sites-enabled:delegated
      - ./.docker/logs:/var/log/apache2:delegated
    networks:
      vpcbr:
        ipv4_address: 172.23.0.3
    extra_hosts:
      - "sof.lc:172.23.0.3"
      - "backend.sof.lc:172.23.0.3"
      - "api.sof.lc:172.23.0.3"
      - "static.sof.lc:172.23.0.3"
    links:
      - mongo
      - redis

  mongo:
    image: mongo:4.0.9
    networks:
      vpcbr:
        ipv4_address: 172.23.0.4
    volumes:
      - ./backups:/backups/sof
      - /var/www/docker/mongodb/sof:/data/db

  redis:
    image: redis:5.0.5
    restart: always
    networks:
      vpcbr:
        ipv4_address: 172.23.0.5

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - subnet: 172.23.0.0/24