<?php

namespace common\models;

use MongoDB\BSON\Timestamp;

/**
 * Class Comment
 * @property string    question
 * @property string    _user
 * @property Timestamp timestamp
 * @property string    _poll
 * @property Poll      poll
 * @property integer   vote
 * @package common\models
 */
class PollVote extends MongoModel
{
    public function behaviors()
    {
        return []; // TODO: Change the autogenerated stub
    }

    public static function collectionName()
    {
        return 'poll_vote';
    }

    public function attributes()
    {
        return [
            '_id',
            '_user',
            '_poll',
            'vote',
            'timestamp',
        ];
    }

    public function rules()
    {
        return [
            [['_user', '_poll', 'vote'], 'safe'],
            [['search'], 'safe', 'on' => 'search'],
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->timestamp = new Timestamp(1, time());
        }
        return parent::beforeSave($insert);
    }

    public function getPoll()
    {
        return $this->hasOne(Poll::className(), ['_id' => '_poll']);
    }
}


