<?php

namespace console\models;

use common\models\Category;
use common\models\Page;
use common\models\Post;
use common\models\Tag;
use common\models\User;
use MongoDB\BSON\Timestamp;

/**
 * Class WPPost
 * @property string ID
 * @property string post_author
 * @property string post_date
 * @property string post_date_gmt
 * @property string post_content
 * @property string post_title
 * @property string post_excerpt
 * @property string post_status
 * @property string comment_status
 * @property string ping_status
 * @property string post_password
 * @property string post_name
 * @property string to_ping
 * @property string pinged
 * @property string post_modified
 * @property string post_modified_gmt
 * @property string post_content_filtered
 * @property string post_parent
 * @property string guid
 * @property string menu_order
 * @property string post_type
 * @property string post_mime_type
 * @property string comment_count
 * @property WPTerms[] postTerms
 */
class WPPost extends WPBase
{
    public $created_at;
    public $updated_at;
    const TYPE_POST     = 'post';
    const TYPE_POST_CAT = 'category';
    const TYPE_POST_TAG = 'post_tag';

    const TYPE_REVIEW     = 'review';
    const TYPE_REVIEW_CAT = 'review-category';
    const TYPE_REVIEW_TAG = 'review-brand';

    const TYPE_PAGE = 'page';

    public static function tableName()
    {
        return '{{%posts}}';
    }

    public function getPostTerms()
    {
        return $this->hasMany(WPTaxonomyRelation::class, ['object_id' => 'ID'])->with('taxonomy');
    }

    public function afterFind()
    {

        $this->created_at = new Timestamp(1, self::getTimestamp($this->post_date));
        $this->updated_at = new Timestamp(1, self::getTimestamp($this->post_modified));
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    private static function getTimestamp($time)
    {
        $datetime = new \DateTime($time);
        return $datetime->getTimestamp();
    }

}