<?php

namespace frontend\models;

use yii\helpers\ArrayHelper;
use yii\mongodb\ActiveQuery;

class PostQuery extends ActiveQuery
{
    public function active($fields = [])
    {
        return $this->select(
            ArrayHelper::merge([
                                   'title',
                                   'slug',
                                   'short_id',
                                   'is_main',
                                   'status',
                                   'info',
                                   'image',
                                   '_categories',
                                   '_translations',
                                   'published_on',
                                   'audio',
                                   'views',
                                   'views_l3d',
                                   'views_l7d',
                                   'read_min',
                                   'is_tagged',
                                   'is_bbc',
                                   '_author',
                               ], $fields))
                    ->andFilterWhere(['status' => PostProvider::STATUS_PUBLISHED]);
    }

    /**
     * @param null $db
     * @return PostProvider[]|array|\yii\mongodb\ActiveRecord
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return PostProvider|array|null|\yii\mongodb\ActiveRecord
     */
    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }
}